# Data Analysis with Pandas

### Data Reading

In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("client_list.csv")

In [4]:
df2=pd.read_csv("client_list.table", sep='\t')

In [5]:
df3=pd.read_fwf("client_list.txt")

In [6]:
pd.read_csv("client_list.csv", skiprows=3, header=None)

           0         1  2   3       4      5
0    Michael   Johnson  M  55     red  green
1       Mary     Adams  F  42  blonde   blue
2     Robert  Phillips  M  37  blonde  brown
3     Thomas     Moore  M  60   brown   blue
4    Natalie    Potter  F  21   brown  green
5     Brenda     Jones  F  18  blonde  brown
6    Michael     Smith  M  58   brown  brown
7   Jennifer     Smith  F  36   black  brown
8    Michael     Smith  M  37   black  hazel
9    Jessica    Rabbit  F  19   black   blue
10     Molly    Bryant  F  21   brown   blue
11     Jaime  Anderson  F  46   brown  green

In [7]:
df=pd.read_csv("client_list.csv")

In [12]:
df.columns = df.columns.str.upper()

In [13]:
df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'GENDER', 'AGE', 'HAIR_COLOR', 'EYE_COLOR'], dtype='object')

In [14]:
pd.read_csv("client_list_practice.csv",usecols=['FIRST_NAME', 'LAST_NAME', 'GENDER', 'AGE', 'HAIR_COLOR', 'EYE_COLOR'])

   FIRST_NAME LAST_NAME GENDER   AGE HAIR_COLOR EYE_COLOR
0    Jennifer     Jones      F  27.0      black     brown
1       Jaime   Roberts      M  32.0      brown     hazel
2     Michael   Johnson      M  55.0        red     green
3        Mary       NaN      F  42.0     blonde       NaN
4         NaN  Phillips      M  37.0        NaN     brown
5      Thomas     Moore      M  60.0      brown      blue
6     Natalie    Potter      F   NaN      brown     green
7      Brenda     Jones      F   NaN        NaN     brown
8     Michael     Smith    NaN  58.0      brown     brown
9    Jennifer     Smith      F  36.0      black     brown
10    Michael     Smith      M  37.0      black     hazel
11    Jessica       NaN      F  19.0      black      blue
12      Molly    Bryant      F  21.0      brown      blue
13      Jaime  Anderson      F  46.0      brown     green

### Data Slicing

In [17]:
df.iloc[5:12]

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel
11    Jessica    Rabbit      F   19      black      blue

In [18]:
df.loc[5:11]

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel
11    Jessica    Rabbit      F   19      black      blue

In [21]:
df[['LAST_NAME', 'AGE', 'HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
0      Jones   27      black
1    Roberts   32      brown
2    Johnson   55        red
3      Adams   42     blonde
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black
12    Bryant   21      brown
13  Anderson   46      brown

In [22]:
df.loc[:,['LAST_NAME', 'AGE', 'HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
0      Jones   27      black
1    Roberts   32      brown
2    Johnson   55        red
3      Adams   42     blonde
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black
12    Bryant   21      brown
13  Anderson   46      brown

In [28]:
df.loc[5:11,['LAST_NAME', 'AGE', 'HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black

In [27]:
df[5:12][['LAST_NAME', 'AGE', 'HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black

### Simple Queries

In [30]:
df[df['LAST_NAME'] == 'Smith']

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

In [32]:
df[df['HAIR_COLOR'] != 'black']

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
1       Jaime   Roberts      M   32      brown     hazel
2     Michael   Johnson      M   55        red     green
3        Mary     Adams      F   42     blonde      blue
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
12      Molly    Bryant      F   21      brown      blue
13      Jaime  Anderson      F   46      brown     green

In [35]:
df.loc[df["HAIR_COLOR"]=="red","HAIR_COLOR"]="ginger"

### Complex Queries

In [40]:
df[(df["AGE"]>30)&(df['GENDER'] == 'F')]

   FIRST_NAME LAST_NAME GENDER   AGE HAIR_COLOR EYE_COLOR
3        Mary     Adams      F  42.0     blonde      blue
9    Jennifer     Smith      F  36.0      black     brown
13      Jaime  Anderson      F  46.0      brown     green

In [42]:
df.loc[(df["AGE"]>30)&(df['GENDER'] == 'F'), ['HAIR_COLOR', 'EYE_COLOR']]

   HAIR_COLOR EYE_COLOR
3      blonde      blue
9       black     brown
13      brown     green

In [43]:
df.loc[(df["AGE"]>25)&(df['GENDER'] == 'F'), ['HAIR_COLOR', 'EYE_COLOR']].drop_duplicates()

   HAIR_COLOR EYE_COLOR
0       black     brown
3      blonde      blue
13      brown     green

In [50]:
df2=pd.read_csv("customer_id_list.csv")

In [51]:
df

    FIRST_NAME LAST_NAME GENDER   AGE HAIR_COLOR EYE_COLOR
0     Jennifer     Jones      F  27.0      black     brown
1        Jaime   Roberts      M  32.0      brown     hazel
2      Michael   Johnson      M  55.0     ginger     green
3         Mary     Adams      F  42.0     blonde      blue
4       Robert  Phillips      M  37.0     blonde     brown
5       Thomas     Moore      M  60.0      brown      blue
6      Natalie    Potter      F  21.0      brown     green
7       Brenda     Jones      F  18.0     blonde     brown
8      Michael     Smith      M  58.0      brown     brown
9     Jennifer     Smith      F  36.0      black     brown
10     Michael     Smith      M  37.0      black     hazel
11     Jessica    Rabbit      F  19.0      black      blue
12       Molly    Bryant      F  21.0      brown      blue
13       Jaime  Anderson      F  46.0      brown     green
red        NaN       NaN    NaN   NaN     ginger       NaN

In [54]:
clients = pd.merge(df, df2, on=['FIRST_NAME',"LAST_NAME","GENDER","AGE"])

In [55]:
df3=pd.read_csv("purchase_log.csv")

In [56]:
df3

   CUSTOMER_ID        DATE    SKU           ITEM_DESCRIPTION   PRICE
0           14  03/17/2014   3844                  green tie   14.99
1            9  02/14/2015  23493          box of chocolates   29.99
2           11  03/01/2015  60385  Nike Lunarglide 6-size8.5  109.99
3            1  01/01/2015  39490                    aspirin   12.99
4            4  10/31/2014  94586           Superman costume   39.99
5            2  12/24/2014  39933                  gift card   50.00
6            9  02/14/2015  38349        bottle of champagne  199.99
7            6  09/13/2014  22495              birthday card    3.99

In [57]:
clients

   FIRST_NAME LAST_NAME GENDER   AGE HAIR_COLOR EYE_COLOR  CUSTOMER_ID
0    Jennifer     Jones      F  27.0      black     brown            1
1       Jaime   Roberts      M  32.0      brown     hazel            2
2     Michael   Johnson      M  55.0     ginger     green            3
3        Mary     Adams      F  42.0     blonde      blue            4
4      Robert  Phillips      M  37.0     blonde     brown            5
5      Thomas     Moore      M  60.0      brown      blue            6
6     Natalie    Potter      F  21.0      brown     green            7
7      Brenda     Jones      F  18.0     blonde     brown            8
8     Michael     Smith      M  58.0      brown     brown            9
9    Jennifer     Smith      F  36.0      black     brown           10
10    Michael     Smith      M  37.0      black     hazel           11
11    Jessica    Rabbit      F  19.0      black      blue           12
12      Molly    Bryant      F  21.0      brown      blue           13
13      Jaime  Anderson      F  46.0      brown     green           14

In [58]:
detailed_sales=pd.merge(df3,clients,on=["CUSTOMER_ID"],how="inner")

In [60]:
detailed_sales

,CUSTOMER_ID,DATE,SKU,ITEM_DESCRIPTION,PRICE,FIRST_NAME,LAST_NAME,GENDER,AGE,HAIR_COLOR,EYE_COLOR
0,14,03/17/2014,3844,green tie,14.99,Jaime,Anderson,F,46.0,brown,green
1,9,02/14/2015,23493,box of chocolates,29.99,Michael,Smith,M,58.0,brown,brown
2,11,03/01/2015,60385,Nike Lunarglide 6-size8.5,109.99,Michael,Smith,M,37.0,black,hazel
3,1,01/01/2015,39490,aspirin,12.99,Jennifer,Jones,F,27.0,black,brown
4,4,10/31/2014,94586,Superman costume,39.99,Mary,Adams,F,42.0,blonde,blue
5,2,12/24/2014,39933,gift card,50.00,Jaime,Roberts,M,32.0,brown,hazel
6,9,02/14/2015,38349,bottle of champagne,199.99,Michael,Smith,M,58.0,brown,brown
7,6,09/13/2014,22495,birthday card,3.99,Thomas,Moore,M,60.0,brown,blue

In [61]:
spenders=detailed_sales.groupby(["FIRST_NAME", "LAST_NAME"])["PRICE"].sum().reset_index()

In [62]:
spenders_sorted = spenders.sort_values(by="PRICE", ascending=False)

In [64]:
spenders_sorted.head(1)

  FIRST_NAME LAST_NAME   PRICE
4    Michael     Smith  339.97

In [65]:
top_spender_first = spenders_sorted.iloc[0]['FIRST_NAME']
top_spender_last = spenders_sorted.iloc[0]['LAST_NAME']

In [66]:
top_client_purchases = detailed_sales[(detailed_sales['FIRST_NAME'] == top_spender_first) & (detailed_sales['LAST_NAME'] == top_spender_last)]

In [68]:
top_client_purchases['ITEM_DESCRIPTION'].unique()

array(['box of chocolates', 'Nike Lunarglide 6-size8.5',
       'bottle of champagne'], dtype=object)

### Writing Files

In [69]:
spenders_sorted.to_csv("top_spenders.csv", index=False)

In [70]:
detailed_sales.to_excel("sales_record.xlsx", sheet_name="Detailed_Sales", index=False)